# Generated by Django 4.2.27 on 2026-06-19 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations, models


def backfill_chapter_locks(apps, schema_editor):
    Chapter = apps.get_model("stories", "Chapter")
    Chapter.objects.filter(order__gt=4).update(is_locked=True)
    Chapter.objects.filter(order__lte=4).update(is_locked=False)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0009_assign_default_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='locked_chapter_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='purchase_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChapterRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='stories.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.RunPython(backfill_chapter_locks, migrations.RunPython.noop),
    ]
