# Generated by Django 4.2.27 on 2026-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_chapter_analytics_and_monetization'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark as completed when the series has ended.'),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
