# Generated by Django 4.2.27 on 2026-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_story_series_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show as the hero story on the homepage.'),
        ),
    ]
