# Generated by Django 4.2.27 on 2026-09-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_story_is_featured'),
        ('accounts', '0004_authorapplication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_read_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.chapter'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_read_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.story'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
