# Generated by Django 4.2.27 on 2026-06-19 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='short_covers/')),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('relationship', 'Mahusiano'), ('heartbreak', 'Huzuni'), ('family', 'Familia'), ('campus', 'Campus'), ('inspiration', 'Inspiration'), ('mystery', 'Mystery'), ('life_lessons', 'Life Lessons')], max_length=32)),
                ('read_time', models.PositiveSmallIntegerField(default=1, help_text='Minutes')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_premium', models.BooleanField(default=False, editable=False)),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_short_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'short stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortStoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('short_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='shorts.shortstory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_story_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortStoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='shorts.shortstory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_story_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shortstoryview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('short_story', 'user'), name='unique_short_view_per_user'),
        ),
        migrations.AddConstraint(
            model_name='shortstoryview',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('short_story', 'session_key'), name='unique_short_view_per_session'),
        ),
        migrations.AddConstraint(
            model_name='shortstorylike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('short_story', 'user'), name='unique_short_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='shortstorylike',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('short_story', 'session_key'), name='unique_short_like_per_session'),
        ),
    ]
